# Generated by Django 3.2.4 on 2021-07-12 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='act_id',
        ),
        migrations.AddField(
            model_name='protectionlevel',
            name='act_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.act'),
        ),
        migrations.AlterField(
            model_name='process',
            name='identifier',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.CreateModel(
            name='SubProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=6)),
                ('name', models.CharField(max_length=250)),
                ('act_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.act')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='subprocess',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subprocess'),
        ),
    ]
