# Generated by Django 3.2.4 on 2021-07-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210712_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='subprocess',
        ),
        migrations.AddField(
            model_name='process',
            name='subprocess',
            field=models.ManyToManyField(to='main.SubProcess'),
        ),
    ]
