# Generated by Django 3.2.4 on 2021-07-22 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210722_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='process',
        ),
        migrations.RemoveField(
            model_name='subprocess',
            name='act_id',
        ),
        migrations.AddField(
            model_name='process',
            name='act_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.act'),
        ),
        migrations.AddField(
            model_name='subprocess',
            name='measure',
            field=models.ManyToManyField(to='main.Measure'),
        ),
    ]
