# Generated by Django 3.2.4 on 2021-08-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_act_process_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='process_id',
        ),
    ]
