# Generated by Django 3.2.4 on 2021-08-12 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_act_process_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='process_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.process'),
        ),
    ]
