# Generated by Django 3.2.4 on 2021-08-16 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_act_process_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='act_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='main.act'),
        ),
    ]
