# Generated by Django 3.2.4 on 2021-08-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_process_act_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='subprocess',
        ),
        migrations.AddField(
            model_name='process',
            name='subprocesses',
            field=models.ManyToManyField(related_name='subprocesses', to='main.SubProcess'),
        ),
    ]
