# Generated by Django 3.2.4 on 2021-08-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210816_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subprocess',
            old_name='measure',
            new_name='measures',
        ),
    ]
