# Generated by Django 3.2.4 on 2021-09-06 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210816_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='main.devicetype'),
        ),
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='main.sentence')),
            ],
        ),
    ]
